In [1]:
from IPython.core.completerlib import import_re
from sklearn.datasets import fetch_california_housing

housing = fetch_california_housing()

In [2]:
print(type(housing))

<class 'sklearn.utils._bunch.Bunch'>

In [3]:
housing.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'feature_names', 'DESCR'])

In [4]:
housing.feature_names

['MedInc',
 'HouseAge',
 'AveRooms',
 'AveBedrms',
 'Population',
 'AveOccup',
 'Latitude',
 'Longitude']

In [5]:
#Creating dataframe
import pandas as pd

df = pd.DataFrame(
    housing.data,
    columns=housing.feature_names
)

df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25

In [6]:
df.shape

(20640, 8)

In [7]:
df.columns

Index(['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup',
       'Latitude', 'Longitude'],
      dtype='str')

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   MedInc      20640 non-null  float64
 1   HouseAge    20640 non-null  float64
 2   AveRooms    20640 non-null  float64
 3   AveBedrms   20640 non-null  float64
 4   Population  20640 non-null  float64
 5   AveOccup    20640 non-null  float64
 6   Latitude    20640 non-null  float64
 7   Longitude   20640 non-null  float64
dtypes: float64(8)
memory usage: 1.3 MB

In [9]:
#Adding target to DataFrame
df["HousePrice"] = housing.target
df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,HousePrice
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

In [10]:
df.shape

(20640, 9)

In [11]:
#Creating separate dataframes for features and target
X = df.drop("HousePrice", axis=1)
y = df["HousePrice"]

In [12]:
X.shape

(20640, 8)

In [13]:
y.shape

(20640,)

In [14]:
type(X)

pandas.DataFrame

In [15]:
type(y)

pandas.Series

In [16]:
# Splitting dataframes into train & test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [18]:
X_train.shape

(16512, 8)

In [19]:
X_test.shape

(4128, 8)

In [21]:
y_train.shape

(16512,)

In [22]:
y_test.shape

(4128,)

In [23]:
#Training Linear Regression Model with training data
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [24]:
#Making Predictions using Linear Regression model
predictions = model.predict(X_test)

In [25]:
predictions

array([0.71912284, 1.76401657, 2.70965883, ..., 4.46877017, 1.18751119,
       2.00940251], shape=(4128,))

In [26]:
#Creating DataFrame for comparing Prediction & Actual Values
comparison = pd.DataFrame({
    "Actual" : y_test,
    "Predicted" : predictions
})

comparison.head()

        Actual  Predicted
20046  0.47700   0.719123
3024   0.45800   1.764017
15663  5.00001   2.709659
20484  2.18600   2.838926
9814   2.78000   2.604657

In [27]:
#Evaluating Linear Regression Model using MAE
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test, predictions)
print(mae)

0.5332001304956555

In [28]:
#Using Decision Tree Model for predictions
from sklearn.tree import DecisionTreeRegressor
tree_model = DecisionTreeRegressor(random_state=42)
tree_model.fit(X_train, y_train)
tree_predictions = tree_model.predict(X_test)

In [29]:
#Evaluating Decision Tree using MAE
from sklearn.metrics import mean_absolute_error
tree_mae = mean_absolute_error(y_test, tree_predictions)
print(tree_mae)

0.4541711942829458

In [30]:
#Using Random Forest model and evaluating using MAE
from sklearn.ensemble import RandomForestRegressor
forest_model = RandomForestRegressor(random_state=42)
forest_model.fit(X_train, y_train)
forest_predictions = forest_model.predict(X_test)
forest_mae = mean_absolute_error(y_test, forest_predictions)
print(forest_mae)

0.32773108008720936

In [31]:
df.columns

Index(['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup',
       'Latitude', 'Longitude', 'HousePrice'],
      dtype='str')

In [32]:
#Figuring out feature importance
feature_importance = pd.DataFrame({
    "Feature" : X.columns,
    "Importance" : forest_model.feature_importances_,
})

feature_importance = feature_importance.sort_values(
    by="Importance",
    ascending=False
)

feature_importance

      Feature  Importance
0      MedInc    0.524980
5    AveOccup    0.138367
6    Latitude    0.089035
7   Longitude    0.088474
1    HouseAge    0.054602
2    AveRooms    0.044216
4  Population    0.030662
3   AveBedrms    0.029663

In [34]:
#Creating new dataframe with top features(Feature selection)

top_features = [
    "MedInc",
    "AveOccup",
    "Latitude",
    "Longitude",
    "HouseAge"
]

X_top = df[top_features]
y = df["HousePrice"]

In [36]:
#Splitting Data for new model

X_train_top, X_test_top, y_train_top, y_test_top = train_test_split(
    X_top,
    y,
    test_size=0.2,
    random_state=42
)

In [37]:
#New Random Forest Model with top features

forest_model_top = RandomForestRegressor()
forest_model_top.fit(X_train_top, y_train_top)
predictions_top = forest_model_top.predict(X_test_top)

#Evaluation for new RF
mae_top = mean_absolute_error(y_test_top, predictions_top)
print(mae_top)

0.32388473624031017

In [40]:
# Creating Multiple RFs with different no. of trees

rf_10 = RandomForestRegressor(
    n_estimators= 10,
    random_state= 42
)

rf_10.fit(X_train, y_train)
pred_10 = rf_10.predict(X_test)

mae_10 = mean_absolute_error(y_test, pred_10)

print(f'RF-10 MAE: {mae_10}')

RF-10 MAE: 0.34849272795542635

In [41]:
rf_50 = RandomForestRegressor(
    n_estimators= 50,
    random_state= 42
)

rf_50.fit(X_train, y_train)
pred_50 = rf_50.predict(X_test)

mae_50 = mean_absolute_error(y_test, pred_50)

print(f'RF-50 MAE: {mae_50}')

RF-50 MAE: 0.3297969649224806

In [42]:
rf_200 = RandomForestRegressor(
    n_estimators= 200,
    random_state= 42
)

rf_200.fit(X_train, y_train)
pred_200 = rf_200.predict(X_test)

mae_200 = mean_absolute_error(y_test, pred_200)

print(f'RF-200 MAE: {mae_200}')

RF-200 MAE: 0.32679018196463205

In [43]:
# import joblib
# joblib.dump(forest_model_top, "../models/house_price_model.pkl")

['house_price_model.pkl']

In [46]:
import os
print(os.getcwd())
print(os.listdir())

C:\Users\Faizur Rahman\PycharmProjects\HousePricePrediction
['.idea', '.venv', 'house_price_model.pkl', 'house_price_prediction.ipynb', 'main.py']

In [47]:
# import joblib
# loaded_model = joblib.load("../models/house_price_model.pkl")

In [48]:
loaded_predictions = loaded_model.predict(X_test_top[:5])
print(loaded_predictions)

[0.48958   0.75761   4.8857339 2.66691   2.46011  ]

In [49]:
original_predictions = forest_model_top.predict(X_test_top[:5])
print(original_predictions)

[0.48958   0.75761   4.8857339 2.66691   2.46011  ]